### ISSUE TITLE
demo link not working

### ISSUE THREAD

**Issue by kirantpatil** [GAKUEngine/gaku#349]
Hi,

How it is compared to fedena ?

Demo link is not working, so please update the link.

Thanks.

**Comment by Kagetsuki** [comment]
The demo was taken down as we have not had the time to maintain it. Currently progress on GAKU has been mostly halted due to lack of funds. Development will continue as soon as we can gather enough funds to bring us roughly to beta release.

The difference from fedena is that GAKU is mostly focused on keeping extremely detailed records. For example: while fedena only keeps course grades, GAKU keeps grades for every assignment and exam. GAKU is also designed to be modular, whereas fedena is mostly monolithic. There are quite a few other differences that we believe would make GAKU a superior solution once the system is completed, but, in its current state GAKU is not yet fully usable much less comparable.

Thank you for your interest nonetheless.
